name: Build and Deploy to Pages
"on":
  push:
    branches:
      - main
  workflow_dispatch: null
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v1
        id: pages
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"
          cache: pnpm
      - run: pnpm i
      - run: pnpm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
